# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: America/Los_Angeles

# jekyll-seo-tag settings
# ↓ --------------------------

title: Daxia's Notes

tagline: Find it more easy at anytime

description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# Fill in the protocol & hostname for your site.
url: "https://wabol.github.io"

github:
  username: wabol

twitter:
  username: twitter_username

social:
  name: Daxia
  email: example@domain.com
  fediverse_handle:
  links:
    - https://twitter.com/username
    - https://github.com/username

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: "G-CR6N58SHGC"
  goatcounter:
    id:
  umami:
    id: "3e0a6a9c-e6e1-462b-bcc7-22e9a15fb38e"
    domain: "https://tj.698423.xyz"
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

# Prefer color scheme setting.
theme_mode:

# The CDN endpoint for media resources.
cdn: "https://chirpy-img.netlify.app"

# the avatar on sidebar, support local or CORS resources
avatar: "https://raw.githubusercontent.com/lyducka/pic/master/uPic/avatar-new.png"

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image:

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: giscus
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo: wabol/wabol.github.io
    repo_id: R_kgDOJvfX7Q
    category: Announcements
    category_id: DIC_kwDOJvfX7c4CXSTE
    mapping: pathname
    strict:
    input_position: bottom
    lang: en
    reactions_enabled:

# Self-hosted static assets, optional
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
